plugins { id 'com.android.application' }

android {
    namespace 'com.comboapp.chat'
    compileSdk 35

    defaultConfig {
        applicationId 'com.comboapp.chat'
        minSdk 23
        targetSdk 35
        versionCode 51
        versionName '5.1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.activity:activity:1.10.1'
    implementation 'androidx.webkit:webkit:1.13.0'
}
